name = "go_over"
version = "2.4.0"
licences = ["MIT"]
repository = { type = "github", user = "bwireman", repo = "go-over" }
description = "A tool to audit Erlang & Elixir dependencies, to make sure your Gleam ✨ projects really sparkle!"
gleam = ">= 1.4.0"
links = [
  { title = "Advisories Source", href = "https://github.com/mirego/elixir-security-advisories" },
]

internal_modules = ["*"]
target = "erlang"
extra_applications = ["yamerl"]

[javascript]
typescript_declarations = false
runtime = "nodejs"

[javascript.deno]
allow_all = true

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
shellout = ">= 1.6.0 and < 2.0.0"
simplifile = ">= 2.0.0 and < 3.0.0"
filepath = ">= 1.0.0 and < 2.0.0"
tom = ">= 1.0.0 and < 2.0.0"
yamerl = ">= 0.10.0 and < 1.0.0"
gleam_hexpm = ">= 2.0.0 and < 3.0.0"
gleam_json = ">= 2.2.0 and < 3.0.0"
birl = ">= 1.7.0 and < 2.0.0"
gleamsver = ">= 1.0.0 and < 2.0.0"
delay = ">= 1.2.0 and < 2.0.0"
gxyz = ">= 0.1.0 and < 1.0.0"
clip = ">= 1.0.0 and < 2.0.0"
spinner = ">= 1.3.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
cactus = ">= 1.0.0 and < 2.0.0"
birdie = ">= 1.2.3 and < 2.0.0"
pprint = ">= 1.0.4 and < 2.0.0"

[cactus.pre-commit]
actions = [
    { command = "./scripts/format.sh", kind = "binary", files = [".mjs", ".js", ".gleam"] },
    { command = "./scripts/update.sh", kind = "binary" },
    { command = "./scripts/target_test.sh", kind = "binary", args = ["erlang"], files = [".erl", ".gleam", "manifest.toml", "gleam.toml"] },
    { command = "./scripts/target_test.sh", kind = "binary", args = ["javascript", "node"], files = [".mjs", ".js", ".gleam", "manifest.toml", "gleam.toml"] },
    { command = "./scripts/target_test.sh", kind = "binary", args = ["javascript", "deno"], files = [".mjs", ".js", ".gleam", "manifest.toml", "gleam.toml"] },
    { command = "./scripts/target_test.sh", kind = "binary", args = ["javascript", "bun"], files = [".mjs", ".js", ".gleam", "manifest.toml", "gleam.toml"] },
]

[go-over]
cache = true
format = "minimal"
outdated = false

[go-over.ignore]
indirect = false
dev_dependencies = false
severity = []
ids = []
