name = "go_over"
version = "1.1.0"
licences = ["MIT"]
repository = { type = "github", user = "bwireman", repo = "go-over" }
description = "A tool to audit Erlang & Elixir dependencies, to make sure your gleam projects really sparkle! ✨"
gleam = ">= 0.34.1"
links = [
  { title = "AdvisoriesSource", href = "https://github.com/mirego/elixir-security-advisories" },
]

internal_modules = ["go_over/*"]
target = "erlang"
extra_applications = ["yamerl"]

[javascript]
typescript_declarations = false
runtime = "nodejs"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
shellout = ">= 1.6.0 and < 2.0.0"
simplifile = ">= 2.0.0 and < 3.0.0"
filepath = ">= 1.0.0 and < 2.0.0"
tom = ">= 1.0.0 and < 2.0.0"
yamerl = ">= 0.10.0 and < 1.0.0"
gleam_hexpm = ">= 1.0.0 and < 2.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
gleam_json = ">= 2.0.0 and < 3.0.0"
birl = ">= 1.7.0 and < 2.0.0"
gleamsver = ">= 1.0.0 and < 2.0.0"
gleam_hackney = ">= 1.2.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"

[go-over]
cache = true
format = "minimal"
outdated = false
ignore_indirect = false

[go-over.ignore]
packages = []
severity = []
ids = []
