name: Test

on:
  push:
    branches:
      - main
  pull_request:

env:
  otp: "26.0.2"
  gleam: "1.2.0"
  rebar: "3"
  nodelts: 20.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.otp }}
          gleam-version: ${{ env.gleam }}
          rebar3-version: ${{ env.rebar }}
      - run: gleam deps download
      - run: gleam test
      - run: gleam format --check src test

  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.otp }}
          gleam-version: ${{ env.gleam }}
          rebar3-version: ${{ env.rebar }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.nodelts }}
          cache: "npm"
      - run: ./scripts/update.sh
      - run: yarn install

  erlang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.otp }}
          gleam-version: ${{ env.gleam }}
          rebar3-version: ${{ env.rebar }}
      - run: gleam run --target erlang

  node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["${{ env.nodelts }}", 22.x]
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.otp }}
          gleam-version: ${{ env.gleam }}
          rebar3-version: ${{ env.rebar }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: yarn install
      - run: gleam run --target javascript --runtime nodejs

  bun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.otp }}
          gleam-version: ${{ env.gleam }}
          rebar3-version: ${{ env.rebar }}
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: gleam run --target javascript --runtime bun
